#!/usr/bin/expect

log_user 0;
set deviceip 	[lindex $argv 0]
set device	[lindex $argv 1]
set user	[lindex $argv 2]
set pass	[lindex $argv 3]

set timeout	360

spawn -noecho ssh -o StrictHostKeyChecking=no $user@$deviceip

expect "*assword: "
send "$pass\r"
expect "$device#"
send "terminal length 0\r"
expect "$device#"
expect *;

log_user 1;
send "show running-config\r"
expect "$device#"
puts $expect_out(buffer);
log_user 0;
send "exit\r"
